/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package me.jiayu.javalin.java;

import io.javalin.Javalin;

public class App {

  public static void main(String[] args) {
    Javalin app = Javalin.create().start(7000);
    app.get("/", ctx -> ctx.json(new VersionInfo("134")));
  }
}
